(define (domain dummy)
  (:requirements :strips :typing :equality)
  (:predicates (goal))
  (:action dummy1 :parameters () :precondition (and) :effect (and))
  (:action dummy2 :parameters () :precondition (   ) :effect (and))
  (:action dummy3 :parameters ()                     :effect (and))
  (:action dummy4 :parameters () :precondition (and) :effect (   ))
  (:action dummy5 :parameters () :precondition (   ) :effect (   ))
  (:action dummy6 :parameters ()                     :effect (   ))
  (:action dummy7 :parameters () :precondition (and)              )
  (:action dummy8 :parameters () :precondition (   )              )
  (:action dummy9 :parameters ()                                  ))
